# Generated by Django 4.2.2 on 2023-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
