# Generated by Django 4.2.2 on 2023-08-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0002_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='number',
            new_name='phone',
        ),
    ]
