# Generated by Django 4.2.2 on 2023-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0003_rename_number_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Tid',
            field=models.CharField(default='001', max_length=3),
        ),
    ]
