# Generated by Django 4.2.2 on 2023-08-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0004_appointment_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Tid',
        ),
        migrations.AddField(
            model_name='appointment',
            name='tid',
            field=models.CharField(default=148294, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
